import type { Question } from '../../../questions/types'

const T = 'math'

export const questions4: Question[] = [
  // ── Inclusion–exclusion
  {
    id: 'math-q-pie-74', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'easy',
    title: 'Divisible by none of 2, 3, 5',
    prompt: 'The page showed that $74$ numbers in $1 \\dots 100$ are divisible by 2, 3 or 5. How many numbers in $1 \\dots 100$ are divisible by **none** of 2, 3, 5? Use the complement form $\\sum_{S} (-1)^{|S|} |A_S|$ with $A_\\emptyset = U$.',
    answer: 26,
    tolerance: 0,
    hint: 'The complement form is $|U|$ minus the union.',
    explain: 'Complement form: $100 - (50 + 33 + 20) + (16 + 10 + 6) - 3 = 100 - 103 + 32 - 3 = 26$, which is exactly $100 - 74$. The empty set contributes $+|U| = 100$, singles are subtracted, pairs added, the triple subtracted — every sign is flipped relative to the union form. A tempting wrong answer is $100 - 103 = -3$ (forgetting the overlaps) or $100 - 103 + 32 = 29$ (stopping before the triple, so the 3 multiples of 30 are wrongly counted as "none").',
  },
  {
    id: 'math-q-pie-lcm-not-product', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'medium',
    title: 'Multiples of 4 or 6',
    prompt: 'How many numbers in $1 \\dots 120$ are divisible by 4 **or** 6?',
    answer: 40,
    tolerance: 0,
    hint: 'A number divisible by both 4 and 6 is divisible by $\\operatorname{lcm}(4, 6)$.',
    explain: '$|A_4 \\cup A_6| = \\lfloor 120/4 \\rfloor + \\lfloor 120/6 \\rfloor - \\lfloor 120/\\operatorname{lcm}(4,6) \\rfloor = 30 + 20 - \\lfloor 120/12 \\rfloor = 30 + 20 - 10 = 40$. Using the **product** $4 \\cdot 6 = 24$ for the intersection gives $30 + 20 - 5 = 45$: it subtracts only the multiples of 24 and leaves 12, 36, 60, 84, 108 counted twice. Product and lcm agree only for coprime divisors; 4 and 6 share the factor 2.',
  },
  {
    id: 'math-q-pie-range', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'medium',
    title: 'A range, not a prefix',
    prompt: 'How many integers in $[50, 150]$ (both ends included) are divisible by 3 or 5? Let $f(n)$ count $[1, n]$ and use the prefix trick.',
    answer: 48,
    tolerance: 0,
    hint: 'The range $[L, R]$ is $f(R) - f(L - 1)$.',
    explain: '$f(n) = \\lfloor n/3 \\rfloor + \\lfloor n/5 \\rfloor - \\lfloor n/15 \\rfloor$. $f(150) = 50 + 30 - 10 = 70$ and $f(49) = 16 + 9 - 3 = 22$, so the answer is $70 - 22 = 48$. The classic slip $f(150) - f(50) = 70 - 23 = 47$ drops the left endpoint 50 itself, which is a multiple of 5 — "in $[L, R]$" is $f(R) - f(L-1)$, not $f(R) - f(L)$.',
  },
  {
    id: 'math-q-pie-coprime-12', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'medium',
    title: 'Coprime to 12 up to 1000',
    prompt: 'How many $x \\in [1, 1000]$ have $\\gcd(x, 12) = 1$?',
    answer: 333,
    tolerance: 0,
    hint: 'Only the **distinct primes** of $12 = 2^2 \\cdot 3$ matter.',
    explain: 'A number shares a factor with 12 exactly when 2 or 3 divides it, so use the complement form over the primes $\\{2, 3\\}$: $1000 - \\lfloor 1000/2 \\rfloor - \\lfloor 1000/3 \\rfloor + \\lfloor 1000/6 \\rfloor = 1000 - 500 - 333 + 166 = 333$. Using 4 instead of 2 (from $2^2$) would miss numbers like 2, 6, 10 that share the factor 2 with 12 — the bad property is "divisible by a prime of $m$", not by a prime power. Sanity check: $\\varphi(12) = 4$, so roughly $1000 \\cdot 4/12 \\approx 333$.',
  },
  {
    id: 'math-q-pie-derange-5', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'easy',
    title: 'Five hats',
    prompt: 'Five guests check their hats and get them back in a random order. In how many of the $5! = 120$ orders does **nobody** get their own hat? Evaluate $D(5) = \\sum_{t=0}^{5} (-1)^t \\binom{5}{t} (5-t)!$.',
    answer: 44,
    tolerance: 0,
    explain: 'The terms $\\binom 5t (5-t)!$ are $120, 120, 60, 20, 5, 1$, so $D(5) = 120 - 120 + 60 - 20 + 5 - 1 = 44$. The recurrence agrees: $D(5) = 4\\,(D(4) + D(3)) = 4\\,(9 + 2) = 44$, and $120/e \\approx 44.1$ rounds to 44. Answering $5! - 5 \\cdot 4! = 0$ stops after the first correction and forgets that permutations with two or more fixed points were subtracted several times.',
  },
  {
    id: 'math-q-pie-surj', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'medium',
    title: 'Every box non-empty',
    prompt: 'In how many ways can 5 **distinct** balls go into 3 **distinct** boxes so that no box is empty? (That is, $\\operatorname{Surj}(5, 3)$.)',
    answer: 150,
    tolerance: 0,
    hint: '$\\operatorname{Surj}(n, k) = \\sum_{j=0}^{k} (-1)^j \\binom{k}{j} (k - j)^n$.',
    explain: '$3^5 - \\binom31 2^5 + \\binom32 1^5 - \\binom33 0^5 = 243 - 96 + 3 - 0 = 150$. Bad property $i$ is "box $i$ is empty"; functions avoiding a set of $j$ boxes map into the other $3 - j$, giving $(3 - j)^5$. Dividing by $3! = 6$ gives the Stirling number $S(5, 3) = 25$ — that would be the answer only if the boxes were identical. $243 - 96 = 147$ forgets to add back the functions that miss two boxes (all balls in one box), which were subtracted twice.',
  },
  {
    id: 'math-q-pie-signs', topic: T, page: 'inclusion-exclusion', kind: 'multi', difficulty: 'medium',
    title: 'Getting the signs right',
    prompt: 'Select **all** correct statements about the signs in inclusion–exclusion over sets $A_1, \\dots, A_k$.',
    options: [
      'In the union form $|\\bigcup A_i|$, the term for a subset $S$ has sign $(-1)^{|S|+1}$: odd-sized subsets are added.',
      'In the complement ("none of the properties") form, the empty set contributes $+|U|$ and odd-sized subsets are subtracted.',
      'The union form also includes the empty set, contributing $+|U|$.',
      'The signs work because $\\sum_{t \\ge 0} (-1)^t \\binom{j}{t} = 0$ for every $j \\ge 1$.',
      'In a bitmask loop, the sign of a mask can be read from the parity of its popcount.',
      'An element lying in exactly $j$ of the sets is counted $j$ times by the full formula.',
    ],
    answers: [0, 1, 3, 4],
    explain: 'The union form sums over **non-empty** $S$ with sign $(-1)^{|S|+1}$; the complement form sums over all $S$ (empty included, giving $+|U|$) with sign $(-1)^{|S|}$ — so option 3 is wrong: adding $|U|$ to the union form is the "forgetting / adding the empty set" bug. The proof rests on $\\sum_t (-1)^t\\binom jt = (1-1)^j = 0$ for $j \\ge 1$, which makes an element in $j \\ge 1$ sets contribute exactly **1**, not $j$ (last option is wrong — that is what the naive sum of $|A_i|$ does). The popcount parity of a mask is $|S| \\bmod 2$, hence the sign.',
  },
  {
    id: 'math-q-pie-mobius', topic: T, page: 'inclusion-exclusion', kind: 'array', difficulty: 'medium',
    title: 'Möbius values',
    prompt: 'Write $\\mu(1), \\mu(2), \\dots, \\mu(10)$, separated by commas.',
    answer: [1, -1, -1, 0, -1, 1, -1, 0, 0, 1],
    placeholder: 'e.g. 1, -1, …',
    explain: '$\\mu(1) = 1$. Primes 2, 3, 5, 7 have one prime factor: $-1$. $6 = 2 \\cdot 3$ and $10 = 2 \\cdot 5$ have two distinct primes: $+1$. $4 = 2^2$, $8 = 2^3$ and $9 = 3^2$ are divisible by a square of a prime: $0$ — they are never the product of a *set* of distinct primes, so inclusion–exclusion never produces them. A common mistake is $\\mu(8) = -1$ ("one distinct prime"): any repeated prime makes $\\mu$ zero.',
  },
  {
    id: 'math-q-pie-rec-fill', topic: T, page: 'inclusion-exclusion', kind: 'fill', difficulty: 'medium',
    title: 'Derangements mod p',
    prompt: 'Complete the $O(n)$ table of derangements modulo $p$ using the recurrence from the page.',
    lang: 'python',
    code: `
D = [0] * (N + 1)
D[0] = 1
D[1] = [[0]]
for n in range(2, N + 1):
    D[n] = ([[1]]) * ([[2]] + [[3]]) % MOD`,
    blanks: [
      ['0'],
      ['n - 1', 'n-1'],
      ['D[n - 1]', 'D[n-1]', 'D[n - 2]', 'D[n-2]'],
      ['D[n - 2]', 'D[n-2]', 'D[n - 1]', 'D[n-1]'],
    ],
    explain: '$D(0) = 1$ (the empty permutation has no fixed point), $D(1) = 0$ (the only permutation of one element fixes it), and $D(n) = (n-1)\\big(D(n-1) + D(n-2)\\big)$: element 1 goes to one of $n-1$ positions $j$; then either $j$ swaps back ($D(n-2)$) or it does not ($D(n-1)$). Only additions and multiplications are used, so no modular inverse is needed. Writing $n$ instead of $n - 1$ as the factor counts position 1 itself, which is forbidden.',
  },
  {
    id: 'math-q-pie-exact-k', topic: T, page: 'inclusion-exclusion', kind: 'numeric', difficulty: 'medium',
    title: 'Exactly two fixed points',
    prompt: 'How many permutations of $\\{1, \\dots, 6\\}$ have **exactly 2** fixed points?',
    answer: 135,
    tolerance: 0,
    hint: 'Choose the fixed ones, then make sure no other point is fixed.',
    explain: 'Choose the 2 fixed points in $\\binom62 = 15$ ways; the other 4 elements must have **no** fixed point, i.e. form a derangement: $D(4) = 9$. Total $15 \\cdot 9 = 135$. Using $4! = 24$ for the rest ($15 \\cdot 24 = 360$) counts permutations with *at least* 2 fixed points, many of them several times.',
  },

  // ── Probability
  {
    id: 'math-q-prob-cond', topic: T, page: 'probability', kind: 'numeric', difficulty: 'easy',
    title: 'Conditioning on the sum',
    prompt: 'Two fair dice are rolled and the sum is **9**. What is the probability that the first die shows 4? Give a decimal.',
    answer: 0.25,
    tolerance: 0.001,
    explain: 'Conditioning shrinks the sample space to the outcomes with sum 9: $(3,6), (4,5), (5,4), (6,3)$ — four equally likely ordered pairs. One has first die 4, so $P = 1/4$. The unconditional $1/6$ ignores the information; $1/2$ comes from treating $\\{4, 5\\}$ as one unordered outcome, which breaks the "equally likely atoms" rule.',
  },
  {
    id: 'math-q-prob-bayes', topic: T, page: 'probability', kind: 'numeric', difficulty: 'medium',
    title: 'A positive test',
    prompt: 'A disease affects 2% of people. A test detects it 90% of the time, and gives a false positive for 5% of healthy people. You test positive. What is $P(\\text{sick} \\mid +)$? Give a decimal to two places.',
    answer: 0.2687,
    tolerance: 0.005,
    hint: '$P(+) = P(+ \\mid \\text{sick})P(\\text{sick}) + P(+ \\mid \\text{healthy})P(\\text{healthy})$.',
    explain: 'Bayes: $\\frac{0.9 \\cdot 0.02}{0.9 \\cdot 0.02 + 0.05 \\cdot 0.98} = \\frac{0.018}{0.018 + 0.049} = \\frac{0.018}{0.067} \\approx 0.27$. The tempting answer 0.9 is $P(+ \\mid \\text{sick})$ — the conditional flipped the wrong way. Healthy people are 49 times as common, so their 5% false positives outnumber the true positives almost 3 to 1.',
  },
  {
    id: 'math-q-prob-linearity', topic: T, page: 'probability', kind: 'multi', difficulty: 'medium',
    title: 'When is independence needed?',
    prompt: 'Select **all** statements that hold for **any** random variables $X, Y$ on the same finite space (no independence assumed).',
    options: [
      '$E[X + Y] = E[X] + E[Y]$',
      '$E[3X - 2Y] = 3E[X] - 2E[Y]$',
      '$E[XY] = E[X]\\,E[Y]$',
      '$E[I_A] = P(A)$ for an indicator $I_A$',
      'The expected number of fixed points of a random permutation is 1, even though the indicators $[p(i) = i]$ are dependent.',
    ],
    answers: [0, 1, 3, 4],
    explain: 'Linearity is proved by splitting a sum over outcomes, using nothing about the joint behaviour, so options 1, 2 and the fixed-point fact (sum of $n$ indicators each with expectation $1/n$) hold always. $E[I_A] = 1 \\cdot P(A) + 0 = P(A)$ is just the definition. The **product** rule needs independence: with $X = Y$ = one fair coin, $E[XY] = 1/2$ but $E[X]E[Y] = 1/4$.',
  },
  {
    id: 'math-q-prob-geometric', topic: T, page: 'probability', kind: 'numeric', difficulty: 'medium',
    title: 'rand7 from rand5',
    prompt: '`rand7()` is built from `rand5()` by rejection: call `rand5()` twice to get one of 25 equally likely pairs; if the pair is among the first 21, map it to 1..7, otherwise retry. What is the expected number of `rand5()` **calls** per `rand7()`? Give a decimal.',
    answer: 2.381,
    tolerance: 0.01,
    hint: 'Each attempt succeeds with probability $p = 21/25$; the number of attempts is geometric.',
    explain: 'Attempts are independent with success probability $p = 21/25$, so the number of attempts is geometric with mean $1/p = 25/21$. Each attempt costs 2 calls, giving $50/21 \\approx 2.38$. Answering 2 ignores the retries; $25/21 \\approx 1.19$ counts attempts, not calls.',
  },
  {
    id: 'math-q-prob-coupon', topic: T, page: 'probability', kind: 'numeric', difficulty: 'medium',
    title: 'Collect four coupons',
    prompt: 'Each box contains one of **4** coupons, uniformly at random. What is the expected number of boxes until you own all 4? Give a decimal.',
    answer: 8.333,
    tolerance: 0.01,
    explain: 'Split into phases: with $i$ coupons owned, a box is new with probability $\\frac{4-i}{4}$, so phase $i$ lasts $\\frac{4}{4-i}$ boxes on average. By linearity, $E = \\frac44 + \\frac43 + \\frac42 + \\frac41 = 4 H_4 = 4 \\cdot \\frac{25}{12} = \\frac{25}{3} \\approx 8.33$. Answering 4 assumes every box is new; the last coupon alone costs 4 boxes on average.',
  },
  {
    id: 'math-q-prob-inversions', topic: T, page: 'probability', kind: 'numeric', difficulty: 'easy',
    title: 'Expected inversions',
    prompt: 'What is the expected number of inversions (pairs $i < j$ with $p(i) > p(j)$) in a uniformly random permutation of **10** elements?',
    answer: 22.5,
    tolerance: 0.001,
    explain: 'One indicator per pair: there are $\\binom{10}{2} = 45$ pairs, and by symmetry each is inverted with probability $\\frac12$. So $E = 45/2 = 22.5 = \\frac{n(n-1)}{4}$. The indicators are dependent, but linearity does not care. 45 is the *maximum* (a reversed array), not the average.',
  },
  {
    id: 'math-q-prob-modp', topic: T, page: 'probability', kind: 'numeric', difficulty: 'medium',
    title: '7/3 modulo a prime',
    prompt: 'An expected value is exactly $\\frac{7}{3}$. Print it as $P \\cdot Q^{-1} \\bmod (10^9 + 7)$. ($3^{-1} \\equiv 333333336$.)',
    answer: 333333338,
    tolerance: 0,
    explain: '$7 \\cdot 333333336 = 2333333352 \\equiv 2333333352 - 2(10^9 + 7) = 333333338$. Check: $3 \\cdot 333333338 = 1000000014 \\equiv 7$. ✓ Note the residue looks nothing like 2.33 — you cannot compare residues by size, and $\\lfloor 7/3 \\rfloor = 2$ is not the requested answer.',
  },
  {
    id: 'math-q-prob-reservoir', topic: T, page: 'probability', kind: 'mcq', difficulty: 'medium',
    title: 'Who is in the reservoir?',
    prompt: 'Algorithm R keeps a reservoir of $k = 3$ items. After **12** items have streamed past, what is the probability that item number 2 is in the reservoir?',
    options: ['$1$', '$3/12 = 1/4$', '$1/12$', '$1/3$', '$\\left(\\frac{11}{12}\\right)^{10}$'],
    answer: 1,
    explain: 'The invariant proved by induction: after $t \\ge k$ items, **every** item is present with probability $k/t = 3/12$. Item 2 entered with probability 1, but each later item $i$ evicts it with probability $\\frac ki \\cdot \\frac1k = \\frac1i$, so it survives with $\\prod_{i=4}^{12} \\frac{i-1}{i} = \\frac{3}{12}$. "1" forgets evictions; $(11/12)^{10}$ uses the wrong eviction probability; $1/12$ would be right only for $k = 1$.',
  },
  {
    id: 'math-q-prob-naive-shuffle', topic: T, page: 'probability', kind: 'numeric', difficulty: 'hard',
    title: 'The naive shuffle is biased',
    prompt: 'The naive shuffle runs `for i in 0..n-1: swap(a[i], a[randint(0, n-1)])`. For `a = [1, 2, 3]` there are $3^3 = 27$ equally likely choice sequences. How many of them leave the array as `[1, 2, 3]`?',
    answer: 4,
    tolerance: 0,
    hint: 'If every permutation were equally likely, each would get $27/6 = 4.5$ sequences — impossible.',
    explain: 'Enumerating the 27 sequences gives 4 for `[1, 2, 3]`, `[3, 1, 2]` and `[3, 2, 1]`, but 5 for `[1, 3, 2]`, `[2, 1, 3]` and `[2, 3, 1]`. Since 27 is not divisible by 6, no map from 27 equally likely sequences onto 6 permutations can be uniform. Fisher–Yates draws $j$ from the shrinking range $[0, i]$, giving $3 \\cdot 2 = 6$ sequences — one per permutation.',
  },
  {
    id: 'math-q-prob-match', topic: T, page: 'probability', kind: 'match', difficulty: 'medium',
    title: 'Match the expectation',
    prompt: 'Match each quantity with its expected value ($n$ elements, uniformly random permutation unless stated).',
    left: [
      'Fixed points of a random permutation',
      'Inversions of a random permutation',
      'Records ("new maximum" updates) scanning left to right',
      'Trials until the first success, success probability $p$',
      'Boxes until all $n$ coupons are collected',
    ],
    right: ['$1$', '$n(n-1)/4$', '$H_n \\approx \\ln n$', '$1/p$', '$n H_n$'],
    explain: 'Fixed points: $n$ indicators of probability $1/n$. Inversions: $\\binom n2$ pairs, each inverted with probability $1/2$. Records: element $i$ is the maximum of the first $i$ with probability $1/i$. Geometric waiting time: $1/p$ by the tail sum or first-step analysis. Coupon collector: $n$ geometric phases of means $n/(n-i)$ summing to $nH_n$.',
  },

  // ── Number patterns
  {
    id: 'math-q-pat-isqrt-float', topic: T, page: 'number-patterns', kind: 'mcq', difficulty: 'medium',
    title: 'Floating-point square root',
    prompt: 'For $n = 999\\,999\\,999\\,999\\,999\\,999$, what does `(long long) sqrt(n)` (double precision) return, and why?',
    options: [
      '$999\\,999\\,999$ — correct, since $n < 2^{63}$',
      '$1\\,000\\,000\\,000$ — $n$ rounds to $10^{18}$ when converted to a double',
      '$999\\,999\\,999$ — `sqrt` always rounds down',
      'Undefined behaviour — the argument overflows',
    ],
    answer: 1,
    explain: 'A double has a 53-bit mantissa, so $n$ is not representable and converts to exactly $10^{18}$; `sqrt` then returns exactly $10^9$, one more than $\\lfloor \\sqrt n \\rfloor = 999\\,999\\,999$. Fitting in a `long long` says nothing about fitting in a double, and `sqrt` rounds to nearest, not down. Use binary search with `mid <= n / mid` or integer Newton instead.',
  },
  {
    id: 'math-q-pat-mod16', topic: T, page: 'number-patterns', kind: 'multi', difficulty: 'easy',
    title: 'Squares mod 16',
    prompt: 'The fast rejection test looks at `n & 15`. For which residues of $n \\bmod 16$ **might** $n$ be a perfect square? Select all.',
    options: ['0', '1', '2', '4', '8', '9', '12', '15'],
    answers: [0, 1, 3, 5],
    explain: 'Squares are $\\equiv 0, 1, 4, 9 \\pmod{16}$: even numbers $2m$ give $4m^2 \\equiv 0$ or $4$; odd numbers give $(2m+1)^2 = 4m(m+1) + 1 \\equiv 1$ or $9$ because $m(m+1)$ is even. Residues 8 and 12 are multiples of 4 that no square reaches mod 16, and 2 and 15 never occur either. Only 4 of 16 residues survive, so 75% of non-squares are rejected instantly.',
  },
  {
    id: 'math-q-pat-base-neg2', topic: T, page: 'number-patterns', kind: 'text', difficulty: 'medium',
    title: '7 in base −2',
    prompt: 'Write $7$ in base $-2$ (digits 0 and 1, most significant first).',
    accept: ['11011', '11011_(-2)'],
    placeholder: 'digits',
    explain: 'Repeated division with the remainder forced into $[0, 2)$: $7 = -2 \\cdot (-3) + 1$; $-3 = -2 \\cdot 2 + 1$ (truncation gives remainder $-1$, so add 2 and bump the quotient); $2 = -2 \\cdot (-1) + 0$; $-1 = -2 \\cdot 1 + 1$; $1 = -2 \\cdot 0 + 1$. Remainders, least significant first: 1, 1, 0, 1, 1, so $11011_{(-2)} = 16 - 8 + 0 - 2 + 1 = 7$. The ordinary binary $111$ means $4 - 2 + 1 = 3$ in base $-2$.',
  },
  {
    id: 'math-q-pat-floor-sum', topic: T, page: 'number-patterns', kind: 'numeric', difficulty: 'easy',
    title: 'Σ ⌊20/i⌋',
    prompt: 'Compute $\\sum_{i=1}^{20} \\lfloor 20/i \\rfloor$ — equivalently, the total number of divisors of $1, 2, \\dots, 20$.',
    answer: 66,
    tolerance: 0,
    explain: 'By blocks: $20 + 10 + 6 + 5 + 4 + 3$ (for $i = 1..6$) $= 48$, then quotient 2 for $i = 7..10$ ($4 \\cdot 2 = 8$) and quotient 1 for $i = 11..20$ ($10 \\cdot 1 = 10$). Total $48 + 8 + 10 = 66$. Each term $\\lfloor 20/i \\rfloor$ counts the multiples of $i$ up to 20, i.e. how many $k \\le 20$ have $i$ as a divisor — so summing over $i$ counts all divisors.',
  },
  {
    id: 'math-q-pat-blocks', topic: T, page: 'number-patterns', kind: 'array', difficulty: 'medium',
    title: 'The quotient blocks of 20',
    prompt: 'Run the block loop `l = 1; while l <= n: q = n / l; r = n / q; …; l = r + 1` for $n = 20$. List the quotient **q** of each block, in order.',
    answer: [20, 10, 6, 5, 4, 3, 2, 1],
    explain: 'Blocks $[l, r]$: $[1,1]$ q=20, $[2,2]$ q=10, $[3,3]$ q=6, $[4,4]$ q=5, $[5,5]$ q=4, $[6,6]$ q=3, $[7,10]$ q=2, $[11,20]$ q=1. Eight blocks — within the bound $2\\sqrt{20} \\approx 8.9$. Small $l$ gives single-cell blocks with large quotients; the wide blocks come at the end. Note 7, 8, 9 never appear as quotients — they are skipped, not listed.',
  },
  {
    id: 'math-q-pat-block-end', topic: T, page: 'number-patterns', kind: 'numeric', difficulty: 'easy',
    title: 'Where does the block end?',
    prompt: 'For $n = 100$, the block starting at $l = 13$ has quotient $q = \\lfloor 100/13 \\rfloor$. What is its last index $r$?',
    answer: 14,
    tolerance: 0,
    explain: '$q = \\lfloor 100/13 \\rfloor = 7$, and $r = \\lfloor n/q \\rfloor = \\lfloor 100/7 \\rfloor = 14$. Check: $\\lfloor 100/14 \\rfloor = 7$ but $\\lfloor 100/15 \\rfloor = 6$. The indices with quotient $\\ge q$ are exactly $1..\\lfloor n/q \\rfloor$. Writing $r = n/l$ (giving 7) confuses the quotient with the index.',
  },
  {
    id: 'math-q-pat-gcd-sum', topic: T, page: 'number-patterns', kind: 'numeric', difficulty: 'medium',
    title: 'Σ gcd(i, 12)',
    prompt: 'Compute $\\sum_{i=1}^{12} \\gcd(i, 12)$ using $\\sum_{g \\mid n} g \\cdot \\varphi(n/g)$.',
    answer: 40,
    tolerance: 0,
    explain: 'Divisors $g$ of 12 with $\\varphi(12/g)$: $1\\cdot\\varphi(12) + 2\\varphi(6) + 3\\varphi(4) + 4\\varphi(3) + 6\\varphi(2) + 12\\varphi(1) = 4 + 4 + 6 + 8 + 6 + 12 = 40$. Directly: gcds are $1,2,3,4,1,6,1,4,3,2,1,12$, total 40. ✓ The count of $i$ with $\\gcd(i, 12) = g$ is $\\varphi(12/g)$, not $\\varphi(g)$: the $i = gj$ with $\\gcd(j, 12/g) = 1$ are counted by $\\varphi$ of the **cofactor**.',
  },
  {
    id: 'math-q-pat-overflow-fill', topic: T, page: 'number-patterns', kind: 'fill', difficulty: 'medium',
    title: 'Overflow-safe comparisons',
    prompt: 'Fill in the division-based tests so that neither function ever computes a product that could overflow.',
    lang: 'cpp',
    code: `
// true iff a * b > c   (a >= 0, b > 0, c >= 0)
bool mulExceeds(long long a, long long b, long long c) {
    return a > [[0]];
}
// isqrt predicate: is mid * mid <= n ?   (mid >= 1)
bool fits(long long mid, long long n) {
    return mid <= [[1]];
}`,
    blanks: [['c / b', 'c/b', '(c / b)', '(c/b)'], ['n / mid', 'n/mid', '(n / mid)', '(n/mid)']],
    explain: 'For positive integers $a \\cdot b > c \\iff a > \\lfloor c/b \\rfloor$: if $a \\le \\lfloor c/b \\rfloor$ then $ab \\le c$, and if $a \\ge \\lfloor c/b \\rfloor + 1$ then $ab > c$ by the definition of the floor. Integer division is exactly that floor and cannot overflow. The isqrt predicate is the same fact with $a = b = $ mid and $c = n$. Writing `a * b > c` overflows for 64-bit inputs, and `c / b` with floating point loses exactness.',
  },
  {
    id: 'math-q-pat-mul-array', topic: T, page: 'number-patterns', kind: 'array', difficulty: 'medium',
    title: 'Multiply strings before the carry sweep',
    prompt: 'Schoolbook multiplication of `"47"` × `"386"` adds every `a[i] * b[j]` into `res[i + j + 1]` of a 5-cell array (index 0 most significant) **without carrying**. What is `res` before the carry sweep?',
    answer: [0, 12, 53, 80, 42],
    explain: '$a = [4, 7]$, $b = [3, 8, 6]$. res[1] += 4·3 = 12; res[2] += 4·8 + 7·3 = 32 + 21 = 53; res[3] += 4·6 + 7·8 = 24 + 56 = 80; res[4] += 7·6 = 42; res[0] stays 0. Sweeping carries from the right: 42 → 2 carry 4; 84 → 4 carry 8; 61 → 1 carry 6; 18 → 8 carry 1; 1. Result 18142 = 47 · 386. ✓ Cells may hold multi-digit values until the single final sweep.',
  },
  {
    id: 'math-q-pat-digit9', topic: T, page: 'number-patterns', kind: 'numeric', difficulty: 'easy',
    title: 'Digital root',
    prompt: 'What is the digital root of $98765$ (repeat the digit sum until one digit remains)?',
    answer: 8,
    tolerance: 0,
    explain: '$9 + 8 + 7 + 6 + 5 = 35 \\to 3 + 5 = 8$. In $O(1)$: since $10 \\equiv 1 \\pmod 9$, a number and its digit sum agree mod 9, and the digital root is $1 + (n - 1) \\bmod 9 = 1 + 98764 \\bmod 9 = 1 + 7 = 8$. Writing $n \\bmod 9$ happens to give 8 here too, but it returns 0 instead of 9 for multiples of 9 — that is why the formula shifts by one.',
  },

  // ── Cheatsheet
  {
    id: 'math-q-cheat-recognize', topic: T, page: 'cheatsheet', kind: 'match', difficulty: 'medium',
    title: 'If the problem says X, think Y',
    prompt: 'Match each problem phrasing with the technique to reach for.',
    left: [
      '"Nobody gets their own gift"',
      '"Count numbers up to $10^{18}$ divisible by any of these 12 numbers"',
      '"Pick a uniformly random node of a linked list of unknown length in one pass"',
      '"Sum of $\\lfloor n/i \\rfloor$ for $n = 10^{12}$"',
      '"$\\binom{n}{k} \\bmod p$ with $n \\le 10^{18}$ and $p$ a small prime"',
      '"Expected number of …"',
    ],
    right: [
      'Derangements $D(n) = (n-1)(D(n-1) + D(n-2))$',
      'Inclusion–exclusion by bitmask with capped lcms',
      'Reservoir sampling with $k = 1$',
      'Quotient blocks, $O(\\sqrt n)$',
      "Lucas' theorem",
      'Linearity of expectation with indicators',
    ],
    explain: 'Each phrasing names its pattern: "nobody … own" is a derangement; "divisible by any of" a union over subsets with lcms (capped at $n$ to avoid overflow); "unknown length, one pass" rules out counting first and calls for reservoir sampling; $\\lfloor n/i \\rfloor$ takes at most $2\\sqrt n$ values; huge $n$ with small prime $p$ breaks factorial tables ($n! \\equiv 0$) but Lucas works digit by digit; and "expected number" is a sum of indicator probabilities.',
  },
  {
    id: 'math-q-cheat-constraints', topic: T, page: 'cheatsheet', kind: 'match', difficulty: 'medium',
    title: 'Constraints → technique',
    prompt: 'Match each constraint with the technique it usually points to.',
    left: [
      '$k \\le 20$ divisors / primes',
      '$n \\le 5000$, $\\binom nk$ modulo an arbitrary $m$',
      '$n \\le 10^7$, answer for every number up to $n$',
      'a single $n \\le 10^{12}$',
      '$n \\le 10^{18}$',
    ],
    right: [
      'subset enumeration, $2^k$ terms',
      "Pascal's triangle, $O(n^2)$, no inverses",
      'a sieve, $O(n)$ or $O(n \\log\\log n)$',
      'trial division / divisor enumeration, $O(\\sqrt n)$',
      '$O(\\log n)$: fast power, Euclid, Miller–Rabin',
    ],
    explain: 'Budget about $10^7$–$10^8$ operations: $2^{20} \\approx 10^6$ subsets; $n^2 = 2.5 \\cdot 10^7$ for Pascal, which needs only additions so works for a non-prime modulus; a sieve is linear-ish in $n$; $\\sqrt{10^{12}} = 10^6$; and at $10^{18}$ even $\\sqrt n = 10^9$ is too slow, leaving logarithmic methods. A sieve up to $10^{12}$ or trial division on $10^{18}$ would blow the time limit.',
  },
  {
    id: 'math-q-cheat-needs-inverse', topic: T, page: 'cheatsheet', kind: 'multi', difficulty: 'medium',
    title: 'Which ones need a modular inverse?',
    prompt: 'Working modulo the prime $p = 10^9 + 7$, which computations **need** a modular inverse as written? Select all.',
    options: [
      '$\\binom{n}{r} = \\frac{n!}{r!\\,(n-r)!}$ from factorial tables',
      'Derangements $D(n)$ by the recurrence $(n-1)(D(n-1) + D(n-2))$',
      "$\\binom nr$ for $n \\le 5000$ by Pascal's triangle",
      'An expected value $\\frac{7}{2}$ printed as $P \\cdot Q^{-1}$',
      '$a^b \\bmod p$ by square-and-multiply',
      'The Catalan number $\\frac{1}{n+1}\\binom{2n}{n}$ from factorial tables',
    ],
    answers: [0, 3, 5],
    explain: 'Any division mod $p$ becomes multiplication by an inverse: the factorial formula divides by $r!(n-r)!$ (use the inverse-factorial table), $7/2$ needs $2^{-1}$, and Catalan divides by $n+1$. The derangement recurrence, Pascal\'s rule $\\binom nr = \\binom{n-1}{r-1} + \\binom{n-1}{r}$ and fast power use only $+$ and $\\times$, so they need no inverse — which is exactly why Pascal works even for non-prime moduli.',
  },
  {
    id: 'math-q-cheat-order-ie', topic: T, page: 'cheatsheet', kind: 'order', difficulty: 'easy',
    title: 'Solving a "none of" counting problem',
    prompt: 'Put the steps of an inclusion–exclusion solution in order.',
    items: [
      'Name the bad properties $A_1, \\dots, A_k$',
      'Find how to count objects having a given set $S$ of bad properties (e.g. $\\lfloor n / \\operatorname{lcm} \\rfloor$)',
      'Check the cost: $2^k$ subsets — prune or reduce if $k$ is large',
      'Loop over every subset mask, sign $(-1)^{|S|}$ by popcount parity',
      'Sum the signed counts (empty set gives $+|U|$) and reduce mod $p$ if asked',
    ],
    explain: 'You first decide *what* is bad, then how to count a fixed set of bad properties (the step that makes the method work — counting objects that *have* properties is easy), then check $2^k$ is affordable before writing the loop, and finally run the signed sum. Jumping to the bitmask loop before knowing how to count $|A_S|$ — or before checking $k$ — is the usual way to get stuck.',
  },
  {
    id: 'math-q-cheat-fib-mod', topic: T, page: 'cheatsheet', kind: 'numeric', difficulty: 'medium',
    title: 'Fibonacci by matrix power',
    prompt: 'Using $\\begin{pmatrix}1&1\\\\1&0\\end{pmatrix}^n = \\begin{pmatrix}F_{n+1}&F_n\\\\F_n&F_{n-1}\\end{pmatrix}$ with $F_0 = 0, F_1 = 1$, compute $F_{30} \\bmod 1000$.',
    answer: 40,
    tolerance: 0,
    explain: '$F_{30} = 832040$, so $F_{30} \\bmod 1000 = 40$. Matrix power takes $O(\\log n)$ $2 \\times 2$ multiplications (reduce mod $m$ after each), which is what makes $n = 10^{18}$ feasible; the top-right entry of $M^{30}$ is $F_{30}$. Reading the top-left entry gives $F_{31} = 1346269 \\to 269$, the off-by-one to avoid.',
  },
  {
    id: 'math-q-cheat-lucas', topic: T, page: 'cheatsheet', kind: 'numeric', difficulty: 'hard',
    title: "Lucas' theorem",
    prompt: 'Compute $\\binom{60}{10} \\bmod 7$ with Lucas\' theorem.',
    answer: 4,
    tolerance: 0,
    hint: 'Write 60 and 10 in base 7.',
    explain: '$60 = 1\\cdot 49 + 1 \\cdot 7 + 4 = (1, 1, 4)_7$ and $10 = (0, 1, 3)_7$. Lucas: $\\binom{60}{10} \\equiv \\binom10 \\binom11 \\binom43 = 1 \\cdot 1 \\cdot 4 = 4 \\pmod 7$. Factorial tables fail here: $60! \\equiv 0 \\pmod 7$ has no inverse. If any digit of $r$ exceeded the matching digit of $n$ (e.g. $\\binom{50}{12}$: digits $(1,0,1)$ vs $(0,1,5)$), the product — and the binomial mod 7 — would be 0.',
  },
]
