import { codeQ } from '../../assemble'

const T = 'arrays'

/** Judged coding problems — one per problem in scripts/learn/problems/arrays.py. */
export const codeQuestions = [
  codeQ(T, 'arr-c-sum', 'traversal', 'Sum of the array', 'easy', 'Read n numbers and print their sum. Values can be large — mind the type.'),
  codeQ(T, 'arr-c-max-min', 'traversal', 'Maximum and minimum', 'easy', 'Print the largest and the smallest value in one pass.'),
  codeQ(T, 'arr-c-second', 'traversal', 'Second largest distinct', 'medium', 'Print the second largest distinct value, or -1 if there is none.'),
  codeQ(T, 'arr-c-insert', 'insert-delete', 'Insert at a position', 'easy', 'Insert x at position p and print the new array.'),
  codeQ(T, 'arr-c-delete', 'insert-delete', 'Delete at a position', 'easy', 'Delete the element at position p and print the array.'),
  codeQ(T, 'arr-c-linear-search', 'searching', 'First occurrence', 'easy', 'Print the index of the first occurrence of x, or -1.'),
  codeQ(T, 'arr-c-count', 'searching', 'Answer occurrence queries', 'medium', 'For each query value, print how many times it occurs.'),
  codeQ(T, 'arr-c-reverse', 'reverse-rotate', 'Reverse the array', 'easy', 'Print the array in reverse, reversing it in place.'),
  codeQ(T, 'arr-c-rotate', 'reverse-rotate', 'Rotate right by k', 'medium', 'Rotate the array right by k (k can exceed n).'),
  codeQ(T, 'arr-c-range-sum', 'prefix-sums', 'Range sum queries', 'medium', 'Answer q range-sum queries fast.'),
  codeQ(T, 'arr-c-equilibrium', 'prefix-sums', 'Equilibrium index', 'medium', 'First index where the sum on the left equals the sum on the right.'),
  codeQ(T, 'arr-c-range-add', 'prefix-sums', 'Many range additions', 'medium', 'Apply m range additions, then print the array.'),
  codeQ(T, 'arr-c-pair-sum', 'two-pointers', 'Pair with sum in a sorted array', 'easy', 'Decide whether two different positions sum to T.'),
  codeQ(T, 'arr-c-dedupe', 'two-pointers', 'Remove duplicates from a sorted array', 'easy', 'Print how many unique values, then the values.'),
  codeQ(T, 'arr-c-move-zeroes', 'two-pointers', 'Move zeroes to the end', 'easy', 'Keep the order of the non-zero values.'),
  codeQ(T, 'arr-c-window-max', 'sliding-window', 'Best window of size k', 'easy', 'Maximum sum of k consecutive elements.'),
  codeQ(T, 'arr-c-min-len', 'sliding-window', 'Shortest subarray with sum ≥ S', 'medium', 'Positive values; print 0 if impossible.'),
  codeQ(T, 'arr-c-longest-ones', 'sliding-window', 'Longest run of ones with k flips', 'medium', 'Flip at most k zeroes to ones; longest block of ones.'),
  codeQ(T, 'arr-c-kadane', 'kadane', 'Maximum subarray sum', 'medium', 'The largest sum of a non-empty contiguous subarray.'),
  codeQ(T, 'arr-c-transpose', '2d-arrays', 'Transpose a matrix', 'easy', 'Print the transpose of an R × C matrix.'),
  codeQ(T, 'arr-c-spiral', '2d-arrays', 'Spiral order', 'medium', 'Print the matrix elements in clockwise spiral order.'),
  codeQ(T, 'arr-c-rotate-matrix', '2d-arrays', 'Rotate a square matrix', 'medium', 'Rotate an N × N matrix 90° clockwise in place.'),
  codeQ(T, 'arr-c-leaders', 'traversal', 'Leaders of an array', 'easy', 'Print every element greater than all elements to its right.'),
  codeQ(T, 'arr-c-majority', 'traversal', 'Majority element', 'medium', 'Print the value that appears more than n/2 times, or -1 — in O(1) extra space.'),
  codeQ(T, 'arr-c-dutch', 'two-pointers', 'Sort 0s, 1s and 2s', 'medium', 'Sort in one pass without counting.'),
  codeQ(T, 'arr-c-merge', 'two-pointers', 'Merge two sorted arrays', 'easy', 'Merge A and B into one sorted array in O(n + m).'),
  codeQ(T, 'arr-c-missing-number', 'index-as-hash', 'The missing number', 'easy', 'n distinct numbers from 0…n — find the one that is missing in O(1) extra space.'),
  codeQ(T, 'arr-c-find-duplicates', 'index-as-hash', 'All duplicates', 'medium', 'Values are 1…n; print every value that appears twice, using the array itself as the "seen" table.'),
  codeQ(T, 'arr-c-first-missing', 'index-as-hash', 'First missing positive', 'hard', 'The smallest positive integer that is absent — O(n) time, O(1) space via cyclic sort.'),
  codeQ(T, 'arr-c-subarray-sum-k', 'prefix-hashing', 'Count subarrays with sum k', 'medium', 'Count subarrays summing to k when values can be negative.'),
  codeQ(T, 'arr-c-longest-sum-k', 'prefix-hashing', 'Longest subarray with sum k', 'medium', 'The longest subarray with sum exactly k, negatives allowed.'),
  codeQ(T, 'arr-c-product-except', 'prefix-hashing', 'Product of array except self', 'medium', 'Every product but your own, without division, modulo 1e9+7.'),
  codeQ(T, 'arr-c-equal-zero-one', 'prefix-hashing', 'Equal zeros and ones', 'medium', 'The longest subarray with as many 0s as 1s.'),
  codeQ(T, 'arr-c-range-sum-2d', 'range-2d', 'Rectangle sum queries', 'medium', 'Answer many rectangle-sum queries in O(1) each with a 2D prefix sum.'),
  codeQ(T, 'arr-c-range-add-2d', 'range-2d', 'Rectangle updates', 'medium', 'Apply many rectangle additions with a 2D difference array.'),
  codeQ(T, 'arr-c-three-sum', 'k-sum', '3-sum: count the triplets', 'medium', 'Count distinct value triplets with sum 0 in O(n²).'),
  codeQ(T, 'arr-c-four-sum', 'k-sum', '4-sum: count the quadruplets', 'hard', 'Count distinct value quadruplets with sum T in O(n³).'),
  codeQ(T, 'arr-c-three-closest', 'k-sum', '3-sum closest', 'medium', 'The triplet sum closest to a target.'),
  codeQ(T, 'arr-c-container', 'water-problems', 'Container with most water', 'medium', 'Two walls holding the most water — and why you move the shorter one.'),
  codeQ(T, 'arr-c-trap-rain', 'water-problems', 'Trapping rain water', 'hard', 'Total water trapped between bars, in O(n) time and O(1) space.'),
  codeQ(T, 'arr-c-exactly-k-odd', 'window-counting', 'Subarrays with exactly k odd numbers', 'medium', 'Exactly k = at most k − at most k−1.'),
  codeQ(T, 'arr-c-k-distinct', 'window-counting', 'At most k distinct values', 'medium', 'The longest window with at most k distinct values.'),
  codeQ(T, 'arr-c-window-maxima', 'window-counting', 'Sliding window maximum', 'hard', 'Every window’s maximum in O(n) with a monotonic deque.'),
  codeQ(T, 'arr-c-stock', 'kadane', 'Best time to buy and sell', 'easy', 'One buy, one later sell — maximum profit in one pass.'),
  codeQ(T, 'arr-c-max-product', 'kadane-variants', 'Maximum product subarray', 'medium', 'Track the max and the min product — a negative swaps them.'),
  codeQ(T, 'arr-c-circular-max', 'kadane-variants', 'Maximum circular subarray', 'medium', 'Best subarray when it may wrap around: total minus the worst middle.'),
  codeQ(T, 'arr-c-one-deletion', 'kadane-variants', 'Max subarray with one deletion', 'hard', 'Kadane with two states: no deletion yet, one deletion used.'),
  codeQ(T, 'arr-c-majority-n3', 'majority-vote', 'More than n/3 times', 'medium', 'Boyer–Moore with two candidates and verification.'),
  codeQ(T, 'arr-c-set-zeroes', 'matrix-techniques', 'Set matrix zeroes', 'medium', 'Zero every row and column holding a 0 — with O(1) extra space.'),
  codeQ(T, 'arr-c-staircase', 'matrix-techniques', 'Search a sorted matrix', 'medium', 'Walk the staircase from the top-right corner: O(R + C) per query.'),
  codeQ(T, 'arr-c-next-permutation', 'reverse-rotate', 'Next permutation', 'medium', 'Pivot, swap, reverse the suffix — O(n) in place.'),
  codeQ(T, 'arr-c-dyn-copies', 'amortized-analysis', 'Cost of a growing array', 'easy', 'Count the copies a doubling array makes for n pushes, n up to 1e18.'),
]
