import type { Question } from '../../../questions/types'

const T = 'arrays'

/* k-sum · water problems · window counting */
export const questions4: Question[] = [
  {
    id: 'arr-q-ks-lookup-first', topic: T, page: 'k-sum', kind: 'mcq', difficulty: 'medium',
    title: 'Insert first, look up second?',
    prompt: 'A two-sum solution inserts `a[j]` into the map **before** looking up `T − a[j]`. On `a = [3, 4]`, `T = 6`, what can it return?',
    options: ['(0, 1)', '(0, 0) — it pairs the 3 with itself', 'Nothing — it correctly reports no pair', 'It crashes'],
    answer: 1,
    explain: 'At j = 0 it inserts 3, then looks up 6 − 3 = 3 and finds index 0: the same element twice. Looking up before inserting guarantees the partner is an earlier, different index.',
  },
  {
    id: 'arr-q-ks-3sum-trace', topic: T, page: 'k-sum', kind: 'numeric', difficulty: 'easy',
    title: 'Distinct triplets',
    prompt: 'How many **distinct** value triplets sum to 0 in `[−1, 0, 1, 2, −1, −4]`?',
    answer: 2,
    explain: 'Sorted: −4 −1 −1 0 1 2. The triplets are (−1, −1, 2) and (−1, 0, 1). The second −1 would find (−1, 0, 1) again, which is why repeated anchors are skipped.',
  },
  {
    id: 'arr-q-ks-skip-wrong', topic: T, page: 'k-sum', kind: 'mcq', difficulty: 'hard',
    title: 'Looking the wrong way',
    prompt: 'A 3-sum skips an anchor when `a[i] == a[i + 1]` (instead of `a[i] == a[i − 1]`). On sorted `[−1, −1, 2]`, what happens?',
    options: [
      'It still finds (−1, −1, 2)',
      'It misses (−1, −1, 2): the first −1 is skipped, and the second −1 has only one element (2) to its right',
      'It reports (−1, −1, 2) twice',
      'It loops forever',
    ],
    answer: 1,
    explain: 'Skipping the *first* copy throws away the anchor whose search range contains the other copy. Skip the *later* copies instead (compare with i − 1): the first copy has already explored every triplet the later ones could.',
  },
  {
    id: 'arr-q-ks-count-less', topic: T, page: 'k-sum', kind: 'numeric', difficulty: 'medium',
    title: 'Triplets below a target',
    prompt: 'How many index triplets i < j < k of `[−2, 0, 1, 3]` have a sum **less than 2**?',
    answer: 2,
    explain: '(−2, 0, 1) = −1 and (−2, 0, 3) = 1 qualify; (−2, 1, 3) = 2 and (0, 1, 3) = 4 do not. The two-pointer count adds hi − lo = 2 in one step when (−2) + 0 + 3 < 2.',
  },
  {
    id: 'arr-q-ks-closest', topic: T, page: 'k-sum', kind: 'numeric', difficulty: 'medium',
    title: '3-sum closest',
    prompt: 'Which triplet sum of `[−1, 2, 1, −4]` is closest to **1**? Give the sum.',
    answer: 2,
    explain: 'Sorted −4 −1 1 2. Sums: −4−1+1 = −4, −4−1+2 = −3, −4+1+2 = −1, −1+1+2 = 2. The closest to 1 is 2 (distance 1).',
  },
  {
    id: 'arr-q-ks-4sum-cost', topic: T, page: 'k-sum', kind: 'mcq', difficulty: 'easy',
    title: 'Cost of 4-sum',
    prompt: 'Sorting plus two nested anchors and a two-pointer scan solves 4-sum in…',
    options: ['O(n²)', 'O(n² log n)', 'O(n³)', 'O(n⁴)'],
    answer: 2,
    explain: 'O(n²) anchor pairs, each followed by an O(n) scan: O(n³). In general k-sum costs O(n^(k−1)) this way.',
  },
  {
    id: 'arr-q-ks-meet', topic: T, page: 'k-sum', kind: 'mcq', difficulty: 'medium',
    title: 'Four arrays',
    prompt: 'Count tuples (i, j, k, l) with A[i] + B[j] + C[k] + D[l] = 0, where each array has n elements. Which approach is O(n²)?',
    options: [
      'Sort all four and use four pointers',
      'Put every A[i] + B[j] in a hash map with counts; for every C[k] + D[l], add the count of its negation',
      'Try all tuples',
      'Binary search D for each (i, j, k)',
    ],
    answer: 1,
    explain: 'Meet in the middle: n² sums on each side, one O(1) lookup each. Trying all tuples is O(n⁴); binary search on D is O(n³ log n).',
  },
  {
    id: 'arr-q-ks-overflow', topic: T, page: 'k-sum', kind: 'mcq', difficulty: 'medium',
    title: 'A sum that does not fit',
    prompt: 'A Java 4-sum computes `int s = a[i] + a[j] + a[lo] + a[hi];` with values up to 10⁹ and target −294967296. It reports a quadruplet of four 10⁹ values. Why?',
    options: [
      'Sorting broke the array',
      '4 × 10⁹ overflows int and wraps around to exactly −294 967 296',
      'The duplicate skipping is wrong',
      'Java ints are 64-bit',
    ],
    answer: 1,
    explain: '4 000 000 000 − 2³² = −294 967 296. Compute the sum in long: `long s = (long) a[i] + a[j] + a[lo] + a[hi];`.',
  },

  // ── Water problems
  {
    id: 'arr-q-wa-container', topic: T, page: 'water-problems', kind: 'numeric', difficulty: 'easy',
    title: 'Most water',
    prompt: 'Container with most water for heights `[1, 8, 6, 2, 5, 4, 8, 3, 7]`?',
    answer: 49,
    explain: 'Walls at indices 1 (8) and 8 (7): width 7 × height 7 = 49. No other pair does better.',
  },
  {
    id: 'arr-q-wa-shorter', topic: T, page: 'water-problems', kind: 'mcq', difficulty: 'medium',
    title: 'Why discard the shorter wall?',
    prompt: 'With h[lo] ≤ h[hi], why may the algorithm discard lo without trying lo with walls between lo and hi?',
    options: [
      'Because the shorter wall is never part of the answer',
      'Because any such pair is narrower and its height is still at most h[lo], so its area cannot exceed the current one',
      'Because the walls are sorted',
      'Because the answer always uses the tallest wall',
    ],
    answer: 1,
    explain: 'Both factors of the area can only get worse: width strictly shrinks and the height is capped by h[lo]. The shorter wall *can* be in the answer (it was, with the current pair) — it just cannot do better with any closer wall.',
  },
  {
    id: 'arr-q-wa-trap', topic: T, page: 'water-problems', kind: 'numeric', difficulty: 'easy',
    title: 'Trapped water',
    prompt: 'How much water is trapped by `[4, 2, 0, 3, 2, 5]`?',
    answer: 9,
    explain: 'L = 4 4 4 4 4 5, R = 5 5 5 5 5 5, so the levels are 4 everywhere inside: water 0, 2, 4, 1, 2, 0 = 9.',
  },
  {
    id: 'arr-q-wa-column', topic: T, page: 'water-problems', kind: 'numeric', difficulty: 'easy',
    title: 'One column',
    prompt: 'For `[3, 0, 2, 0, 4]`, how much water sits above index 2 (the bar of height 2)?',
    answer: 1,
    explain: 'The tallest bar on its left is 3 and on its right is 4. The level is min(3, 4) = 3, so the water is 3 − 2 = 1.',
  },
  {
    id: 'arr-q-wa-two-why', topic: T, page: 'water-problems', kind: 'mcq', difficulty: 'hard',
    title: 'The two-pointer argument',
    prompt: 'In the O(1)-space solution, when leftMax ≤ rightMax we settle bar lo with water max(leftMax, h[lo]) − h[lo], even though we do not know the true tallest bar to its right. Why is that safe?',
    options: [
      'The tallest bar to the right of lo is at least rightMax ≥ leftMax, so the left side is the limiting one',
      'Because rightMax is always the global maximum',
      'Because the heights are sorted',
      'It is only approximately right',
    ],
    answer: 0,
    explain: 'The right maximum for lo covers h[lo..n−1] ⊇ h[hi+1..n−1], so it is ≥ rightMax ≥ leftMax. The water level min(L, R) is therefore decided by the left side alone.',
  },
  {
    id: 'arr-q-wa-stack-layer', topic: T, page: 'water-problems', kind: 'numeric', difficulty: 'hard',
    title: 'First layer from the stack',
    prompt: 'Run the monotonic-stack method on `[4, 2, 0, 3, 2, 5]`. When bar 3 (height 3) arrives it pops index 2 (height 0) with left wall index 1 (height 2). How many units does that layer add?',
    answer: 2,
    explain: 'Width = 3 − 1 − 1 = 1, depth = min(2, 3) − 0 = 2, so 1 × 2 = 2. The next pop (index 1, left wall 0) adds width 2 × depth (min(4,3) − 2) = 2.',
  },
  {
    id: 'arr-q-wa-diff', topic: T, page: 'water-problems', kind: 'mcq', difficulty: 'medium',
    title: 'Container vs trapping',
    prompt: 'What is the essential difference between "container with most water" and "trapping rain water"?',
    options: [
      'None — they compute the same number',
      'The container picks two walls and ignores bars between them; trapping counts water above every bar, blocked by the bars in between',
      'Trapping only works on sorted heights',
      'The container needs a stack',
    ],
    answer: 1,
    explain: 'The container asks for one best pair (bars between are treated as absent). Trapping sums the water over all columns of a fixed landscape.',
  },
  {
    id: 'arr-q-wa-match', topic: T, page: 'water-problems', kind: 'match', difficulty: 'medium',
    title: 'Three ways to trap water',
    prompt: 'Match each method with its key idea.',
    left: ['Prefix maxima', 'Two pointers', 'Monotonic stack'],
    right: [
      'water[i] = min(L[i], R[i]) − h[i] with L and R precomputed',
      'The side with the smaller running maximum already knows its water level',
      'A taller bar closes a basin; add one horizontal layer per pop',
    ],
    explain: 'All three are O(n) time; only two pointers is O(1) extra space.',
  },

  // ── Window counting
  {
    id: 'arr-q-wc-count', topic: T, page: 'window-counting', kind: 'numeric', difficulty: 'easy',
    title: 'Counting with hi − lo + 1',
    prompt: 'How many subarrays of `[1, 2, 3]` have sum ≤ 5?',
    answer: 5,
    explain: '[1], [2], [3], [1, 2] = 3, [2, 3] = 5 qualify; [1, 2, 3] = 6 does not. The window adds 1, then 2, then 2 (after shrinking lo to 1) = 5.',
  },
  {
    id: 'arr-q-wc-exactly', topic: T, page: 'window-counting', kind: 'numeric', difficulty: 'medium',
    title: 'Exactly two odds',
    prompt: 'How many subarrays of `[1, 1, 2, 1]` contain **exactly 2** odd numbers?',
    answer: 3,
    explain: '[1, 1], [1, 1, 2] and [1, 2, 1]. With the trick: atMost(2) = 9 (every subarray except the whole array) and atMost(1) = 6, so 9 − 6 = 3.',
  },
  {
    id: 'arr-q-wc-identity', topic: T, page: 'window-counting', kind: 'mcq', difficulty: 'medium',
    title: 'Why not one window for "exactly k"?',
    prompt: 'Why can’t a single shrink-from-the-left window count subarrays with **exactly** k odd numbers?',
    options: [
      'Because odd numbers cannot be counted incrementally',
      'Because "exactly k" is not preserved by shrinking: for a fixed end, the valid starts are a middle band, not everything from lo to hi',
      'Because the answer can exceed n',
      'Because it needs a hash map',
    ],
    answer: 1,
    explain: 'For a fixed right end, the starts giving exactly k odds form a contiguous band in the middle (those giving more are left of it, fewer are right of it). "At most k" is a suffix of starts — monotone — so subtracting two such counts isolates the band.',
  },
  {
    id: 'arr-q-wc-kdistinct', topic: T, page: 'window-counting', kind: 'numeric', difficulty: 'medium',
    title: 'At most 2 distinct',
    prompt: 'Longest subarray of `[1, 2, 1, 2, 3, 3, 2, 2, 4, 1]` with at most 2 distinct values?',
    answer: 5,
    explain: 'a[3..7] = 2 3 3 2 2 has length 5. [1 2 1 2] has length 4, and no window of length 6 has only two distinct values.',
  },
  {
    id: 'arr-q-wc-deque-trace', topic: T, page: 'window-counting', kind: 'array', difficulty: 'medium',
    title: 'Window maxima',
    prompt: 'Sliding window maximum with k = 3 on `[1, 3, −1, −3, 5, 3, 6, 7]`?',
    answer: [3, 3, 5, 5, 6, 7],
    explain: 'Windows: [1 3 −1] → 3, [3 −1 −3] → 3, [−1 −3 5] → 5, [−3 5 3] → 5, [5 3 6] → 6, [3 6 7] → 7.',
  },
  {
    id: 'arr-q-wc-deque-why', topic: T, page: 'window-counting', kind: 'mcq', difficulty: 'hard',
    title: 'Why evict from the back?',
    prompt: 'When a[i] arrives, the deque pops every back index j with a[j] ≤ a[i]. Why can those j never be needed again?',
    options: [
      'Because they are already outside the window',
      'Because j is older than i, so it leaves the window first, and while both are inside a[i] ≥ a[j] — j can never be the unique maximum',
      'Because the deque must stay sorted by index',
      'Because popping keeps the deque short, which is only an optimisation',
    ],
    answer: 1,
    explain: 'Any future window containing j also contains i (i is newer and stays at least as long), and a[i] ≥ a[j]. So j is dominated forever. That domination argument is what makes the deque O(n).',
  },
  {
    id: 'arr-q-wc-circular', topic: T, page: 'window-counting', kind: 'numeric', difficulty: 'medium',
    title: 'Circular window',
    prompt: 'Maximum sum of 3 consecutive elements of the **circular** array `[5, −2, 1, 4, 6]` (windows may wrap around)?',
    answer: 15,
    explain: 'Windows: 5−2+1 = 4, −2+1+4 = 3, 1+4+6 = 11, 4+6+5 = 15 (wraps), 6+5−2 = 9. The best wraps around the end.',
  },
  {
    id: 'arr-q-wc-product', topic: T, page: 'window-counting', kind: 'numeric', difficulty: 'medium',
    title: 'Product below k',
    prompt: 'How many subarrays of `[10, 5, 2, 6]` have a product strictly less than 100?',
    answer: 8,
    explain: 'Per right end: 10 → 1; 5 → 2 ([5], [10,5]); 2 → 2 ([2], [5,2]; 10·5·2 = 100 is not < 100); 6 → 3 ([6], [2,6], [5,2,6] = 60). Total 8.',
  },
  {
    id: 'arr-q-wc-monotone', topic: T, page: 'window-counting', kind: 'multi', difficulty: 'hard',
    title: 'Which conditions suit a plain window?',
    prompt: 'For which conditions is "valid window ⇒ every shorter window with the same right end is valid" true, so the shrink-from-the-left window works directly? Select all.',
    options: [
      'Sum ≤ S, all values positive',
      'At most k distinct values',
      'Exactly k zeros',
      'Sum ≤ S, values may be negative',
      'Product < k, all values ≥ 1',
    ],
    answers: [0, 1, 4],
    explain: 'Dropping elements from the left can only lower a positive sum, the distinct count, or a product of values ≥ 1. "Exactly k" is not preserved, and with negatives dropping an element can raise the sum.',
  },
]
