import type { Question } from '../../../questions/types'

const T = 'arrays'

/* Kadane variants · majority vote · matrix techniques */
export const questions5: Question[] = [
  {
    id: 'arr-q-kv-product', topic: T, page: 'kadane-variants', kind: 'numeric', difficulty: 'easy',
    title: 'Maximum product',
    prompt: 'Maximum product of a contiguous subarray of `[−2, 3, −4]`?',
    answer: 24,
    explain: 'The whole array: (−2) × 3 × (−4) = 24. At index 2 the *minimum* product ending at index 1 (−6) times −4 gives the new maximum.',
  },
  {
    id: 'arr-q-kv-why-min', topic: T, page: 'kadane-variants', kind: 'mcq', difficulty: 'medium',
    title: 'Why track the minimum?',
    prompt: 'Why does the maximum-product algorithm keep the **smallest** product ending at each index, not just the largest?',
    options: [
      'To detect zeros',
      'Because multiplying by a negative number reverses order: the smallest (most negative) product can become the largest',
      'Because the answer can be negative',
      'To make the algorithm stable',
    ],
    answer: 1,
    explain: 'With a negative a[i], the largest product ending at i comes from the smallest one ending at i − 1. One state is not enough to summarise the past; two are.',
  },
  {
    id: 'arr-q-kv-circular', topic: T, page: 'kadane-variants', kind: 'numeric', difficulty: 'easy',
    title: 'Circular maximum',
    prompt: 'Maximum circular subarray sum of `[5, −3, 5]`?',
    answer: 10,
    explain: 'total − min = 7 − (−3) = 10: take 5, wrap, take 5, leaving out the −3 in the middle. Ordinary Kadane gives only 7.',
  },
  {
    id: 'arr-q-kv-allneg', topic: T, page: 'kadane-variants', kind: 'mcq', difficulty: 'hard',
    title: 'The all-negative trap',
    prompt: 'For `[−3, −2, −5]`, the formula max(Kadane_max, total − Kadane_min) returns 0. What is wrong, and what is the correct answer?',
    options: [
      'Nothing — 0 is correct',
      'total − min = 0 corresponds to the empty subarray, which is not allowed; the answer is −2',
      'The minimum should be −2, so the answer is −8',
      'Circular arrays cannot contain negatives',
    ],
    answer: 1,
    explain: 'When every value is negative, the minimum subarray is the whole array and "everything except it" is empty. Return Kadane_max (−2) in that case.',
  },
  {
    id: 'arr-q-kv-deletion', topic: T, page: 'kadane-variants', kind: 'numeric', difficulty: 'medium',
    title: 'One deletion allowed',
    prompt: 'Maximum subarray sum of `[1, −2, 0, 3]` if you may delete **at most one** element from the chosen subarray?',
    answer: 4,
    explain: 'Take [1, −2, 0, 3] and delete −2: 1 + 0 + 3 = 4. Without deletion the best is 3.',
  },
  {
    id: 'arr-q-kv-order', topic: T, page: 'kadane-variants', kind: 'mcq', difficulty: 'hard',
    title: 'Update order',
    prompt: 'In the one-deletion DP, `del = max(keep, del + a[i])` must use the value of `keep` from index i − 1. Why?',
    options: [
      'Because keep is larger',
      'Because "delete a[i]" means the kept part ends at i − 1 — it is the best subarray ending at i − 1 with no deletion',
      'Because del is always negative',
      'The order does not matter',
    ],
    answer: 1,
    explain: 'Deleting a[i] leaves a subarray ending at i − 1. Using the already-updated keep (which includes a[i]) would describe a subarray that both contains and deletes a[i].',
  },
  {
    id: 'arr-q-kv-rect', topic: T, page: 'kadane-variants', kind: 'mcq', difficulty: 'medium',
    title: 'Maximum-sum rectangle',
    prompt: 'Fixing the top and bottom rows and running Kadane on the collapsed column sums finds the maximum-sum rectangle of an R × C matrix in…',
    options: ['O(RC)', 'O(R²C)', 'O(R²C²)', 'O(RC log C)'],
    answer: 1,
    explain: 'O(R²) row pairs, each with an O(C) column update and an O(C) Kadane. Enumerating all rectangles with 2D prefix sums would be O(R²C²).',
  },
  {
    id: 'arr-q-kv-abs', topic: T, page: 'kadane-variants', kind: 'numeric', difficulty: 'medium',
    title: 'Maximum absolute sum',
    prompt: 'What is the maximum of |sum| over all subarrays of `[2, −5, 1, −4, 3, −2]`?',
    answer: 8,
    explain: 'The most negative subarray is −5 + 1 − 4 = −8 (absolute value 8); the largest positive one is 3. So 8. Equivalently, max prefix − min prefix.',
  },

  // ── Majority vote
  {
    id: 'arr-q-mv-proof', topic: T, page: 'majority-vote', kind: 'mcq', difficulty: 'medium',
    title: 'Why the majority survives',
    prompt: 'Which argument proves that Boyer–Moore ends with the majority element when one exists?',
    options: [
      'The majority appears first in the array',
      'Each decrement discards two different values, so at most one copy of the majority per discarded pair — fewer than half its copies can be discarded',
      'The count is always positive',
      'The algorithm sorts the array implicitly',
    ],
    answer: 1,
    explain: 'There are at most n/2 discarded pairs and each contains at most one copy of m. Since m has more than n/2 copies, some copy is never discarded, and the undiscarded elements are all copies of the final candidate.',
  },
  {
    id: 'arr-q-mv-false', topic: T, page: 'majority-vote', kind: 'numeric', difficulty: 'easy',
    title: 'A candidate that is not a majority',
    prompt: 'Run Boyer–Moore on `[1, 2, 3]`. What is the final candidate?',
    answer: 3,
    explain: '1 becomes candidate; 2 cancels it (count 0); 3 becomes candidate. But 3 appears once out of three — not a majority. That is why the verification pass is required.',
  },
  {
    id: 'arr-q-mv-how-many', topic: T, page: 'majority-vote', kind: 'numeric', difficulty: 'medium',
    title: 'How many can exceed n/4?',
    prompt: 'At most how many different values can each occur **more than n/4** times in an array of n elements?',
    answer: 3,
    explain: 'Four such values would need more than 4 · n/4 = n elements. So at most 3 — which is why the n/k version keeps k − 1 candidates.',
  },
  {
    id: 'arr-q-mv-trace', topic: T, page: 'majority-vote', kind: 'array', difficulty: 'medium',
    title: 'Elements above n/3',
    prompt: 'List (in increasing order) every value occurring more than ⌊n/3⌋ times in `[1, 1, 1, 3, 3, 2, 2, 2]`.',
    answer: [1, 2],
    explain: 'n = 8, ⌊8/3⌋ = 2. 1 and 2 each occur 3 times (> 2); 3 occurs only twice.',
  },
  {
    id: 'arr-q-mv-k', topic: T, page: 'majority-vote', kind: 'mcq', difficulty: 'medium',
    title: 'Misra–Gries memory',
    prompt: 'To find every value occurring more than n/k times in one pass, the Misra–Gries summary keeps how many (value, count) pairs?',
    options: ['1', 'k − 1', 'k', 'n/k'],
    answer: 1,
    explain: 'At most k − 1 values can exceed n/k. Each "decrement all" discards k different values, so at most n/k discards happen and every heavy hitter survives.',
  },
  {
    id: 'arr-q-mv-sorted', topic: T, page: 'majority-vote', kind: 'mcq', difficulty: 'medium',
    title: 'Majority in sorted order',
    prompt: 'If an array is sorted and has a majority element (more than n/2 copies), where is it guaranteed to appear?',
    options: ['At index 0', 'At index ⌊n/2⌋', 'At index n − 1', 'Nowhere in particular'],
    answer: 1,
    explain: 'Its copies form one block longer than n/2, so the block must cover the middle position wherever it starts.',
  },

  // ── Matrix techniques
  {
    id: 'arr-q-mt-map', topic: T, page: 'matrix-techniques', kind: 'mcq', difficulty: 'medium',
    title: 'Where does (r, c) go?',
    prompt: 'Rotating an N × N matrix 90° **clockwise**, the element at (r, c) moves to…',
    options: ['(c, r)', '(c, N − 1 − r)', '(N − 1 − c, r)', '(N − 1 − r, N − 1 − c)'],
    answer: 1,
    explain: 'Top-left (0, 0) must go to top-right (0, N − 1): only (c, N − 1 − r) does that. (c, r) is the transpose; (N − 1 − c, r) is counter-clockwise; the last is 180°.',
  },
  {
    id: 'arr-q-mt-rotate-trace', topic: T, page: 'matrix-techniques', kind: 'array', difficulty: 'easy',
    title: 'Rotate a 2 × 2',
    prompt: 'Rotate `[[1, 2], [3, 4]]` 90° clockwise. Write the result row by row as one list.',
    answer: [3, 1, 4, 2],
    explain: 'Transpose → [[1, 3], [2, 4]]; reverse each row → [[3, 1], [4, 2]].',
  },
  {
    id: 'arr-q-mt-ccw', topic: T, page: 'matrix-techniques', kind: 'mcq', difficulty: 'medium',
    title: 'Counter-clockwise',
    prompt: 'Which in-place recipe rotates 90° **counter-clockwise**?',
    options: ['Transpose, then reverse each row', 'Transpose, then reverse the order of the rows', 'Reverse each row twice', 'Transpose twice'],
    answer: 1,
    explain: 'Counter-clockwise maps (r, c) → (N − 1 − c, r). Transpose gives (c, r); reversing the row order sends row c to row N − 1 − c. Transposing twice is the identity.',
  },
  {
    id: 'arr-q-mt-zero-naive', topic: T, page: 'matrix-techniques', kind: 'mcq', difficulty: 'medium',
    title: 'Zeroing as you go',
    prompt: 'Why does "scan the matrix; on finding a 0, immediately zero its row and column" give wrong answers?',
    options: [
      'It is too slow but correct',
      'The zeros it writes are later mistaken for original zeros, so extra rows and columns get cleared',
      'It cannot handle the first row',
      'It never terminates',
    ],
    answer: 1,
    explain: 'After zeroing row r, the scan meets those new zeros and clears their columns too — possibly the whole matrix. Record first, apply second.',
  },
  {
    id: 'arr-q-mt-zero-order', topic: T, page: 'matrix-techniques', kind: 'order', difficulty: 'medium',
    title: 'O(1)-space set zeroes, in order',
    prompt: 'Put the steps of the O(1)-space "set matrix zeroes" in order.',
    items: [
      'Record whether row 0 and column 0 contain an original zero',
      'For each inner zero, write markers into M[r][0] and M[0][c]',
      'Zero every inner cell whose row or column marker is 0',
      'Finally zero row 0 and/or column 0 if their flags are set',
    ],
    explain: 'The flags must be read before the markers overwrite row 0 / column 0, and the edges must be zeroed last so the markers stay readable.',
  },
  {
    id: 'arr-q-mt-staircase', topic: T, page: 'matrix-techniques', kind: 'numeric', difficulty: 'medium',
    title: 'Staircase bound',
    prompt: 'In a 4 × 5 matrix with sorted rows and columns, at most how many comparisons does the staircase search (from the top-right) make?',
    answer: 8,
    explain: 'Every comparison that is not a hit removes one row or one column; after 4 + 5 − 1 = 8 comparisons nothing would be left.',
  },
  {
    id: 'arr-q-mt-corner', topic: T, page: 'matrix-techniques', kind: 'mcq', difficulty: 'medium',
    title: 'Why not the top-left corner?',
    prompt: 'Why can’t the staircase search start at the top-left corner?',
    options: [
      'It can; any corner works',
      'Both neighbours of the top-left are larger, so "corner < x" does not tell you whether to go right or down',
      'The top-left is always the answer',
      'Indexes would go negative',
    ],
    answer: 1,
    explain: 'The top-right and bottom-left corners are larger than one neighbour direction and smaller than the other, so each comparison discards a full row or column. The top-left (and bottom-right) lack that property.',
  },
  {
    id: 'arr-q-mt-flat', topic: T, page: 'matrix-techniques', kind: 'array', difficulty: 'easy',
    title: 'Flattened index',
    prompt: 'A fully sorted 3 × 4 matrix is binary-searched as one array of 12. Which cell is index k = 7? Answer as [row, column].',
    answer: [1, 3],
    explain: 'row = 7 div 4 = 1, column = 7 mod 4 = 3. Divide by the number of **columns**, not rows.',
  },
  {
    id: 'arr-q-mt-spiral2', topic: T, page: 'matrix-techniques', kind: 'array', difficulty: 'easy',
    title: 'Spiral fill',
    prompt: 'Fill a 3 × 3 matrix with 1…9 in clockwise spiral order. Write the result row by row as one list.',
    answer: [1, 2, 3, 8, 9, 4, 7, 6, 5],
    explain: 'Top row 1 2 3, right column 4 5, bottom row backwards 6 7, left column 8, centre 9: [[1,2,3],[8,9,4],[7,6,5]].',
  },
]
