import { codeQ } from '../../assemble'

const T = 'complexity'

/** Judged coding problems — one per problem in scripts/learn/problems/complexity.py. */
export const codeQuestions = [
  codeQ(T, 'cx-c-sum-n', 'why-measure', 'Sum 1 to n, modulo', 'easy', 'n up to 10¹⁸: a loop is hopeless, a formula is O(1). Mind the overflow.'),
  codeQ(T, 'cx-c-distinct', 'loops', 'Count distinct values', 'easy', 'n up to 2·10⁵: replace the pairwise check with sorting.'),
  codeQ(T, 'cx-c-pairs', 'loops', 'Count pairs with sum T', 'medium', 'Count i < j with aᵢ + aⱼ = T — without checking every pair.'),
  codeQ(T, 'cx-c-halvings', 'logarithms', 'How many halvings?', 'easy', 'For each n ≤ 10¹⁸, how many times can you halve it before reaching 1?'),
  codeQ(T, 'cx-c-powmod', 'logarithms', 'Fast modular power', 'medium', 'aᵇ mod m with b up to 10¹⁸ — O(log b) per query.'),
  codeQ(T, 'cx-c-harmonic', 'logarithms', 'Sum of ⌊n / i⌋', 'hard', 'n up to 10¹²: group the i with equal quotients for O(√n).'),
  codeQ(T, 'cx-c-divisors', 'growth-classes', 'Count the divisors', 'easy', 'n up to 10¹²: stop at √n.'),
  codeQ(T, 'cx-c-prime', 'growth-classes', 'Prime or not', 'medium', 'Up to 20 numbers, each up to 10¹².'),
  codeQ(T, 'cx-c-sum-squares', 'summations', 'Sum of squares', 'easy', 'n(n+1)(2n+1)/6 for n up to 10¹⁸ — divide exactly before reducing.'),
  codeQ(T, 'cx-c-div-a-or-b', 'summations', 'Divisible by a or b', 'medium', 'Inclusion–exclusion with the lcm — and no overflow computing it.'),
  codeQ(T, 'cx-c-geometric', 'summations', 'Geometric series', 'hard', '1 + r + … + rᵏ mod p with k up to 10¹⁸ — and the r ≡ 1 trap.'),
  codeQ(T, 'cx-c-triple-loop', 'code-fragments', 'How many times does it run?', 'medium', 'Count runs of a nested i ≤ j ≤ k loop exactly — it is a binomial coefficient.'),
  codeQ(T, 'cx-c-doubling-loop', 'code-fragments', 'A loop that doubles', 'easy', 'Looks like n log n; a geometric series says otherwise.'),
  codeQ(T, 'cx-c-sqrt-chain', 'code-fragments', 'Repeated square roots', 'medium', 'Θ(log log n) steps — and a floating-point sqrt that can lie.'),
  codeQ(T, 'cx-c-digits-base', 'logarithms', 'Digits in base b', 'easy', '⌊log_b n⌋ + 1, computed exactly with integers.'),
  codeQ(T, 'cx-c-power-steps', 'logarithms', 'Smallest power that reaches n', 'medium', '⌈log_c n⌉ without overflowing on the way.'),
  codeQ(T, 'cx-c-squares-range', 'growth-classes', 'Perfect squares in a range', 'easy', '⌊√b⌋ − ⌊√(a−1)⌋ with an exact integer square root.'),
  codeQ(T, 'cx-c-count-primes', 'growth-classes', 'Counting primes', 'medium', '10⁵ queries: sieve once, answer each in O(1).'),
  codeQ(T, 'cx-c-compare-growth', 'growth-classes', 'Which grows faster?', 'medium', 'Compare pⁿ·nᵃ·(log n)ᵇ against another — exponential, then power, then log.'),
  codeQ(T, 'cx-c-big-o-witness', 'asymptotic-proofs', 'Find the Big-O witness', 'hard', 'Given C, find the smallest n₀ that makes the Big-O proof go through.'),
  codeQ(T, 'cx-c-max-pair-product', 'estimating-runtime', 'Largest product of two', 'easy', '2·10¹⁰ pairs is too many — only four values matter.'),
  codeQ(T, 'cx-c-inversions', 'estimating-runtime', 'Counting inversions', 'hard', 'Count them during merge sort in O(n log n).'),
  codeQ(T, 'cx-c-closest-values', 'estimating-runtime', 'Closest pair of values', 'easy', 'After sorting, the closest pair is adjacent.'),
  codeQ(T, 'cx-c-linear-search-cost', 'cases', 'Best case, worst case', 'medium', 'Comparisons made by a linear search — answer each query in O(1).'),
  codeQ(T, 'cx-c-binary-search-cost', 'cases', 'How many probes?', 'medium', 'Simulate binary search and count the probes; never more than ⌊log₂ n⌋ + 1.'),
  codeQ(T, 'cx-c-tree-height', 'space', 'Height of a deep tree', 'medium', 'A path of 2·10⁵ nodes overflows the call stack — go iterative.'),
  codeQ(T, 'cx-c-single-number', 'space', 'The one without a partner', 'easy', 'O(1) extra space: XOR cancels the pairs.'),
  codeQ(T, 'cx-c-counter-flips', 'amortized-methods', 'Binary counter bit flips', 'medium', 'One increment can flip 60 bits, yet the total is under 2n.'),
  codeQ(T, 'cx-c-multipop', 'amortized-methods', 'Stack with multipop', 'medium', 'Each element is popped at most once — O(1) amortised.'),
  codeQ(T, 'cx-c-two-stack-queue', 'amortized-methods', 'A queue from two stacks', 'medium', 'Simulate it and count the moves — amortised O(1) per operation.'),
  codeQ(T, 'cx-c-expected-records', 'expected-analysis', 'Expected number of records', 'hard', 'Indicator variables turn it into the harmonic number Hₙ.'),
  codeQ(T, 'cx-c-coupon', 'expected-analysis', 'Coupon collector', 'hard', 'A sum of geometric waiting times: n·Hₙ.'),
  codeQ(T, 'cx-c-recurrence-eval', 'recurrences', 'Evaluate a divide-and-conquer recurrence', 'medium', 'T(n) = a·T(⌊n/b⌋) + n — only log_b n values to evaluate.'),
  codeQ(T, 'cx-c-two-branch', 'recurrence-methods', 'Two unequal branches, memoised', 'hard', 'T(⌊n/2⌋) + T(⌊n/3⌋) + 1 for n up to 10¹⁸ — few distinct arguments.'),
  codeQ(T, 'cx-c-fib-calls', 'recurrences', 'How many calls does naive Fibonacci make?', 'medium', 'C(k) = 1 + C(k−1) + C(k−2) — exponential growth, counted exactly.'),
  codeQ(T, 'cx-c-karatsuba-leaves', 'recursive-algorithms', 'Karatsuba’s base cases', 'medium', '3 products per level, log₂ n levels: 3^⌈log₂ n⌉ leaves.'),
  codeQ(T, 'cx-c-quicksort-expected', 'recursive-algorithms', 'Expected comparisons of quicksort', 'hard', 'Linearity of expectation over pairs gives 2(n+1)Hₙ − 4n.'),
  codeQ(T, 'cx-c-min-max-count', 'lower-bounds', 'Min, max and the comparisons it takes', 'medium', 'The pairing trick: ⌈3n/2⌉ − 2 comparisons, and no fewer.'),
  codeQ(T, 'cx-c-second-largest', 'lower-bounds', 'The runner-up and its lower bound', 'medium', 'A knockout tournament: n + ⌈log₂ n⌉ − 2 comparisons.'),
  codeQ(T, 'cx-c-subset-count', 'hard-problems', 'Count the subsets (n ≤ 20)', 'medium', 'NP-complete in general — but 2²⁰ bitmasks is fine.'),
  codeQ(T, 'cx-c-subset-mitm', 'hard-problems', 'Count the subsets (n ≤ 40)', 'hard', 'Meet in the middle: 2·2²⁰ instead of 2⁴⁰.'),
  codeQ(T, 'cx-c-knapsack-weight', 'hard-problems', '0/1 knapsack, small capacity', 'hard', 'O(n·W) over capacities — pseudo-polynomial.'),
  codeQ(T, 'cx-c-knapsack-value', 'hard-problems', '0/1 knapsack, huge capacity', 'hard', 'Capacity up to 10⁹: index the table by value instead.'),
  codeQ(T, 'cx-c-pop-front', 'hidden-costs', 'Removing from the front', 'easy', 'pop(0) / shift() is Θ(n) — use a head index or a deque.'),
  codeQ(T, 'cx-c-membership', 'hidden-costs', 'Membership queries', 'easy', '“x in list” is a hidden linear scan — use a set.'),
  codeQ(T, 'cx-c-dominant-term', 'big-o', 'The dominant term', 'easy', 'Drop constants and lower-order terms — carefully.'),
]
