import type { Question } from '../../../questions/types'

const T = 'complexity'

/* Questions for the recurrence-methods, recursive-algorithms, lower-bounds and hard-problems pages. */
export const questions5: Question[] = [
  // ── Solving recurrences
  {
    id: 'cx-q-rm-ratio', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'medium',
    title: 'Who dominates the tree?',
    prompt: 'For $T(n) = 4T(n/2) + n$, the recursion tree has level costs $n, 2n, 4n, \\dots$ Which part of the tree dominates the total, and what is $T(n)$?',
    options: ['The root: Θ(n)', 'All levels equally: Θ(n log n)', 'The leaves: Θ(n²)', 'The leaves: Θ(n² log n)'],
    answer: 2,
    explain: 'The ratio between levels is a/b^k = 4/2 = 2 > 1, so the costs grow geometrically toward the leaves. There are 4^{log₂ n} = n² leaves, and a geometric series is dominated by its largest term: Θ(n²). Θ(n log n) would need ratio exactly 1.',
  },
  {
    id: 'cx-q-rm-master-a', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'easy',
    title: 'Master theorem, case 2',
    prompt: 'Solve $T(n) = 2T(n/2) + \\Theta(n)$.',
    options: ['Θ(n)', 'Θ(n log n)', 'Θ(n²)', 'Θ(log n)'],
    answer: 1,
    explain: 'n^{log_b a} = n^{log₂ 2} = n, and f(n) = Θ(n) matches it exactly (case 2, k = 0), so T(n) = Θ(n log n) — merge sort.',
  },
  {
    id: 'cx-q-rm-master-b', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'medium',
    title: 'Master theorem, case 3',
    prompt: 'Solve $T(n) = 3T(n/4) + n^2$.',
    options: ['Θ(n^{log₄ 3})', 'Θ(n² log n)', 'Θ(n²)', 'Θ(n log n)'],
    answer: 2,
    explain: 'n^{log₄ 3} ≈ n^{0.79}; f(n) = n² is polynomially larger, and the regularity condition holds (3·(n/4)² = (3/16)n² ≤ c·n² with c = 3/16 < 1). Case 3: the root dominates, Θ(n²).',
  },
  {
    id: 'cx-q-rm-gap', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'hard',
    title: 'The gap in the Master theorem',
    prompt: 'Why does the basic Master theorem fail for $T(n) = 2T(n/2) + n/\\log n$?',
    options: [
      'Because a must be at least 3',
      'Because f(n) = n/log n is smaller than n^{log₂ 2} = n, but not polynomially smaller (not O(n^{1−ε}) for any ε > 0)',
      'Because the recurrence has unequal subproblems',
      'Because f(n) is not a polynomial, and the theorem only accepts polynomials',
    ],
    answer: 1,
    explain: 'Case 1 needs f(n) = O(n^{1−ε}); n/log n beats every n^{1−ε} eventually, so it is not. Case 2 needs Θ(n log^k n) with k ≥ 0, and log^{−1} has k = −1. The recurrence falls in the gap; the recursion tree gives Θ(n log log n). The theorem accepts many non-polynomials, e.g. n log n.',
  },
  {
    id: 'cx-q-rm-unequal', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'medium',
    title: 'Lopsided splits',
    prompt: 'Quicksort always splits 1 : 9. Its cost satisfies $T(n) = T(n/10) + T(9n/10) + n$. What is $T(n)$?',
    options: ['Θ(n)', 'Θ(n log n)', 'Θ(n²)', 'Θ(n^{1.1})'],
    answer: 1,
    explain: 'Every full level of the tree costs n, and the depth is between log₁₀ n and log_{10/9} n — both Θ(log n). So T(n) = Θ(n log n); a fixed proportional split only changes the base of the logarithm.',
  },
  {
    id: 'cx-q-rm-substitution', topic: T, page: 'recurrence-methods', kind: 'mcq', difficulty: 'hard',
    title: 'A broken induction',
    prompt: 'A student "proves" $T(n) = 2T(n/2) + n$ is $O(n)$: assume $T(k) \\le ck$ for $k < n$; then $T(n) \\le 2c\\frac n2 + n = cn + n = O(n)$. What is wrong?',
    options: [
      'Nothing — the proof is correct',
      'The base case was skipped',
      'The inductive step must conclude T(n) ≤ cn with the same c; it concluded T(n) ≤ (c + 1)n, so the hypothesis was not reproduced',
      'Induction cannot be used on recurrences',
    ],
    answer: 2,
    explain: 'Substitution proves "T(n) ≤ cn for one fixed c". Ending with (c + 1)n lets the constant grow at every level — over log n levels it becomes c + log n, which is exactly the hidden n log n. The true answer is Θ(n log n).',
  },
  {
    id: 'cx-q-rm-subtract', topic: T, page: 'recurrence-methods', kind: 'numeric', difficulty: 'medium',
    title: 'Unroll a subtracting recurrence',
    prompt: '$T(n) = T(n-1) + n$ with $T(0) = 0$. What is $T(100)$?',
    answer: 5050,
    explain: 'Unrolling gives T(n) = n + (n − 1) + … + 1 = n(n + 1)/2, so T(100) = 5050 and T(n) = Θ(n²). The Master theorem does not apply: the input shrinks by subtraction, not division.',
  },
  {
    id: 'cx-q-rm-match', topic: T, page: 'recurrence-methods', kind: 'match', difficulty: 'medium',
    title: 'Recurrence to complexity',
    prompt: 'Match each recurrence with its solution.',
    left: ['T(n/2) + 1', '2T(n/2) + 1', '2T(n/2) + n', '3T(n/2) + n', 'T(n−1) + 1'],
    right: ['Θ(log n)', 'Θ(n)', 'Θ(n log n)', 'Θ(n^{log₂ 3})', 'Θ(n) by unrolling'],
    explain: 'T(n/2)+1 is binary search; 2T(n/2)+1 has n leaves dominating (case 1) — Θ(n); 2T(n/2)+n is merge sort; 3T(n/2)+n is Karatsuba (case 1, leaves); T(n−1)+1 unrolls to n.',
  },

  // ── Analysing recursive algorithms
  {
    id: 'cx-q-ra-bs-space', topic: T, page: 'recursive-algorithms', kind: 'mcq', difficulty: 'easy',
    title: 'Stack space of binary search',
    prompt: 'How much extra space does a **recursive** binary search on $n$ elements use?',
    options: ['O(1)', 'O(log n) — one stack frame per halving', 'O(n)', 'O(n log n)'],
    answer: 1,
    explain: 'The calls nest: each waits for the next, and there are at most about log₂ n of them before the range is empty. The iterative version uses O(1).',
  },
  {
    id: 'cx-q-ra-karatsuba', topic: T, page: 'recursive-algorithms', kind: 'numeric', difficulty: 'medium',
    title: 'Counting Karatsuba leaves',
    prompt: 'Karatsuba multiplies two $n$-digit numbers with 3 half-size products per level. For $n = 64$ (a power of 2), how many one-digit multiplications happen at the bottom of the recursion tree?',
    answer: 729,
    explain: 'There are log₂ 64 = 6 levels of splitting and each node has 3 children, so 3⁶ = 729 leaves — versus 64² = 4096 single-digit products for the school method. In general 3^{log₂ n} = n^{log₂ 3}.',
  },
  {
    id: 'cx-q-ra-four-calls', topic: T, page: 'recursive-algorithms', kind: 'mcq', difficulty: 'medium',
    title: 'Four products is no better',
    prompt: 'Divide-and-conquer multiplication with **four** half-size products and linear combine work satisfies $T(n) = 4T(n/2) + O(n)$. How does it compare with the school method?',
    options: ['Faster: Θ(n log n)', 'The same: Θ(n²)', 'Slower: Θ(n² log n)', 'Faster: Θ(n^{1.5})'],
    answer: 1,
    explain: 'n^{log₂ 4} = n² dominates the linear combine (case 1), so it is Θ(n²) — no improvement. Saving a single recursive call (4 → 3) is what lowers the exponent.',
  },
  {
    id: 'cx-q-ra-quick-adjacent', topic: T, page: 'recursive-algorithms', kind: 'mcq', difficulty: 'medium',
    title: 'Neighbours always meet',
    prompt: 'In randomized quicksort, consider the values ranked $i$ and $i + 1$ in sorted order. What is the probability they are compared?',
    options: ['0', '1/2', '1', '2/n'],
    answer: 2,
    explain: 'The probability is 2/(j − i + 1) = 2/2 = 1. No value lies strictly between them, so nothing can separate them: they stay together until one of them becomes the pivot, and then the two are compared.',
  },
  {
    id: 'cx-q-ra-quick-prob', topic: T, page: 'recursive-algorithms', kind: 'numeric', difficulty: 'hard',
    title: 'Probability of a comparison',
    prompt: 'In randomized quicksort on the values 1…10, what is the probability that the values 2 and 7 are compared? Answer as a decimal.',
    answer: 0.3333,
    tolerance: 0.002,
    explain: 'The block 2, 3, 4, 5, 6, 7 has 6 values; they are compared iff the first pivot chosen from this block is 2 or 7: probability 2/6 = 1/3.',
  },
  {
    id: 'cx-q-ra-recurrence-code', topic: T, page: 'recursive-algorithms', kind: 'mcq', difficulty: 'medium',
    title: 'Read the recurrence off the code',
    prompt: 'A function on an array of size $n$ does an $O(n)$ loop, then calls itself on the first half and on the second half, and then once more on the middle half. What is its recurrence and running time?',
    options: ['T(n) = 2T(n/2) + n → Θ(n log n)', 'T(n) = 3T(n/2) + n → Θ(n^{log₂ 3})', 'T(n) = 3T(n/3) + n → Θ(n log n)', 'T(n) = T(n/2) + n → Θ(n)'],
    answer: 1,
    explain: 'Three recursive calls, each on half the input, plus linear work: 3T(n/2) + n. n^{log₂ 3} ≈ n^{1.585} dominates n (case 1).',
  },
  {
    id: 'cx-q-ra-smaller-first', topic: T, page: 'recursive-algorithms', kind: 'mcq', difficulty: 'hard',
    title: 'Bounding quicksort’s stack',
    prompt: 'Quicksort recurses into the **smaller** part and loops (no recursion) on the larger part. What is the worst-case recursion depth?',
    options: ['O(1)', 'O(log n)', 'O(√n)', 'O(n)'],
    answer: 1,
    explain: 'Every recursive call is on a part of at most half the current size, so after d nested calls the size is at most n/2^d: depth ≤ log₂ n — even when the pivots are terrible (the time can still be Θ(n²)).',
  },

  // ── Lower bounds
  {
    id: 'cx-q-lb-leaves', topic: T, page: 'lower-bounds', kind: 'numeric', difficulty: 'easy',
    title: 'Leaves for sorting 4 items',
    prompt: 'A comparison sort on 4 distinct elements is drawn as a decision tree. What is the **minimum number of leaves** it must have?',
    answer: 24,
    explain: 'Each of the 4! = 24 input orders needs a different rearrangement, so each needs its own leaf.',
  },
  {
    id: 'cx-q-lb-log-fact', topic: T, page: 'lower-bounds', kind: 'numeric', difficulty: 'medium',
    title: 'Minimum worst-case comparisons',
    prompt: 'What is the least number of comparisons that **every** comparison sort needs in the worst case to sort 5 distinct elements? (Use the decision-tree bound.)',
    answer: 7,
    explain: '5! = 120 leaves; a binary tree of height h has at most 2^h leaves, and 2⁶ = 64 < 120 ≤ 128 = 2⁷. So h ≥ ⌈log₂ 120⌉ = 7. (Seven comparisons are in fact achievable for 5 elements.)',
  },
  {
    id: 'cx-q-lb-counting', topic: T, page: 'lower-bounds', kind: 'mcq', difficulty: 'medium',
    title: 'Beating n log n?',
    prompt: 'Counting sort sorts $n$ integers in $[0, k]$ in $O(n + k)$. Why does that not contradict the $\\Omega(n\\log n)$ sorting lower bound?',
    options: [
      'Because the lower bound only applies to average cases',
      'Because counting sort is not a comparison sort: it uses values as array indices, outside the comparison model',
      'Because k is always larger than n log n',
      'Because the lower bound is wrong for integers',
    ],
    answer: 1,
    explain: 'The bound holds for algorithms that learn about the input only by comparing pairs. Indexing an array by a value extracts much more information per step.',
  },
  {
    id: 'cx-q-lb-max', topic: T, page: 'lower-bounds', kind: 'numeric', difficulty: 'easy',
    title: 'Finding the maximum',
    prompt: 'What is the minimum number of comparisons that can guarantee finding the maximum of 50 distinct values?',
    answer: 49,
    explain: 'Every non-maximum must lose at least one comparison, and each comparison has exactly one loser, so at least n − 1 = 49. A simple scan achieves it.',
  },
  {
    id: 'cx-q-lb-minmax', topic: T, page: 'lower-bounds', kind: 'numeric', difficulty: 'medium',
    title: 'Min and max together',
    prompt: 'Using the pairing method, how many comparisons find both the minimum and the maximum of 100 values?',
    answer: 148,
    explain: '50 comparisons inside pairs, then 49 among the winners for the max and 49 among the losers for the min: 50 + 49 + 49 = 148 = 3n/2 − 2. The naive two-pass method uses 2n − 2 = 198, and the adversary argument shows 148 is optimal.',
  },
  {
    id: 'cx-q-lb-second', topic: T, page: 'lower-bounds', kind: 'numeric', difficulty: 'hard',
    title: 'Second largest',
    prompt: 'With a knockout tournament, how many comparisons in total find both the largest and the second largest of 64 values?',
    answer: 68,
    explain: 'The tournament finds the largest in 63 comparisons. The second largest lost directly to the champion, who played log₂ 64 = 6 matches, so a final mini-tournament among those 6 takes 5 more: 63 + 5 = 68 = n + ⌈log₂ n⌉ − 2.',
  },
  {
    id: 'cx-q-lb-read', topic: T, page: 'lower-bounds', kind: 'mcq', difficulty: 'medium',
    title: 'Must you read everything?',
    prompt: 'Why does checking whether an unsorted array contains the value 0 require looking at all $n$ elements in the worst case?',
    options: [
      'Because of the n log n sorting bound',
      'Because an adversary can answer "not 0" for every cell read and put the 0 in a cell the algorithm never read — so any algorithm that skips a cell can be fooled',
      'Because arrays do not support random access',
      'It does not — binary search finds it in O(log n)',
    ],
    answer: 1,
    explain: 'An algorithm that stops early leaves some cell unread; the adversary makes that cell 0 or not 0 to contradict whatever it answers. So Ω(n) reads are necessary. Binary search needs the array to be sorted.',
  },

  // ── Hard problems
  {
    id: 'cx-q-hp-double', topic: T, page: 'hard-problems', kind: 'numeric', difficulty: 'easy',
    title: 'One more item',
    prompt: 'A brute-force subset search takes 3 seconds on 30 items. Roughly how many seconds does it take on 33 items?',
    answer: 24,
    explain: 'Each extra item doubles the number of subsets: 2³ = 8 times as many, so about 24 seconds.',
  },
  {
    id: 'cx-q-hp-n20', topic: T, page: 'hard-problems', kind: 'mcq', difficulty: 'easy',
    title: 'Reading the constraint',
    prompt: 'A problem asks for the best subset of items, with $n \\le 20$. What does the constraint suggest?',
    options: [
      'An O(n log n) greedy is expected',
      'An O(2ⁿ · n) enumeration of subsets (bitmask) is fine: about 2·10⁷ operations',
      'The problem is impossible to solve exactly',
      'Recursion is not allowed',
    ],
    answer: 1,
    explain: '2²⁰ ≈ 10⁶ subsets times n = 20 is about 2·10⁷ — well within a second. Small n is the classic signal that exponential search is intended.',
  },
  {
    id: 'cx-q-hp-pseudo', topic: T, page: 'hard-problems', kind: 'mcq', difficulty: 'medium',
    title: 'Pseudo-polynomial',
    prompt: 'The 0/1 knapsack DP runs in $O(nW)$. Why is it called pseudo-polynomial rather than polynomial?',
    options: [
      'Because it uses dynamic programming',
      'Because W is a numeric value; the input stores W in only log₂ W bits, so O(nW) is exponential in the input length',
      'Because it only works for small n',
      'Because its memory is O(n²)',
    ],
    answer: 1,
    explain: 'Polynomial time is measured in the length of the input. Adding one digit to W makes the input one digit longer but the table ten times wider.',
  },
  {
    id: 'cx-q-hp-np-cert', topic: T, page: 'hard-problems', kind: 'mcq', difficulty: 'medium',
    title: 'What makes a problem NP',
    prompt: 'Which property places a yes/no problem in NP?',
    options: [
      'It cannot be solved in polynomial time',
      'Every "yes" instance has a certificate that can be checked in polynomial time',
      'It needs exponential memory',
      'It is solved by backtracking',
    ],
    answer: 1,
    explain: 'NP = efficiently verifiable. For subset sum the certificate is the subset: add it up in O(n). Every problem in P is also in NP, so "NP" does not mean "hard".',
  },
  {
    id: 'cx-q-hp-npc', topic: T, page: 'hard-problems', kind: 'multi', difficulty: 'medium',
    title: 'Spot the NP-complete problems',
    prompt: 'Which of these (decision versions) are NP-complete? Select all that apply.',
    options: ['Hamiltonian path', 'Shortest path in a weighted graph', '3-colouring a graph', 'Minimum spanning tree', 'Subset sum'],
    answers: [0, 2, 4],
    explain: 'Hamiltonian path, 3-colouring and subset sum are classic NP-complete problems. Shortest paths (Dijkstra, Bellman–Ford) and minimum spanning trees (Kruskal, Prim) are solvable in polynomial time.',
  },
  {
    id: 'cx-q-hp-easy-cousin', topic: T, page: 'hard-problems', kind: 'match', difficulty: 'medium',
    title: 'Hard problem, easy cousin',
    prompt: 'Each NP-complete problem on the left has a polynomial-time "cousin". Match them.',
    left: ['Hamiltonian path (visit every vertex once)', '3-colouring', 'Longest simple path', 'Travelling salesman'],
    right: ['Euler path (use every edge once)', '2-colouring (bipartiteness)', 'Shortest path', 'Minimum spanning tree'],
    explain: 'Each pair looks alike but only the right-hand problem has a known polynomial algorithm: Euler paths via degrees and Hierholzer, 2-colouring via BFS, shortest paths via Dijkstra, MST via Kruskal/Prim (and an MST even gives a 2-approximation for metric TSP).',
  },
  {
    id: 'cx-q-hp-mitm', topic: T, page: 'hard-problems', kind: 'mcq', difficulty: 'hard',
    title: 'Meet in the middle',
    prompt: 'Subset sum with $n = 40$ and large values. Which approach is practical?',
    options: [
      'Enumerate all 2⁴⁰ subsets',
      'The O(nT) DP',
      'Split into two halves of 20, list the 2²⁰ subset sums of each, sort one list and binary-search it for T − s for every s of the other',
      'A greedy that takes the largest items first',
    ],
    answer: 2,
    explain: '2⁴⁰ ≈ 10¹² is far too slow and the DP needs T to be small. Meet in the middle costs O(2^{n/2} · n) ≈ 2·10⁷. Greedy is not correct for subset sum.',
  },
]
